# Generated by Django 5.0.2 on 2024-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('total_hrs', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentaccountsdata',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentaccountsdata',
            name='mobile_num',
            field=models.IntegerField(),
        ),
    ]
