# Generated by Django 5.0.2 on 2024-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_timetabledata_alter_studentaccountsdata_logged_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('mobile_num', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentAccountsData',
        ),
        migrations.RenameField(
            model_name='timetabledata',
            old_name='faculty',
            new_name='faculty_name',
        ),
    ]
