# Generated by Django 5.0.2 on 2024-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_useraccountsdata_delete_studentaccountsdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsdata',
            name='batch_subj',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
