# Generated by Django 5.0.2 on 2024-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_useraccountsdata_batch_subj'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabledata',
            name='batch',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
