# Generated by Django 5.0.2 on 2024-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_faculty_student_timetable_delete_timetabledata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subjet',
            field=models.CharField(default='FSD-2', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
