# Generated by Django 5.0.2 on 2024-09-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0007_faculty_subjet_alter_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='subjet',
            new_name='subject',
        ),
    ]
