# Generated by Django 5.0.2 on 2024-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_rename_subjet_faculty_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='B1', max_length=50),
            preserve_default=False,
        ),
    ]
