# Generated by Django 5.0.2 on 2024-09-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0010_remove_timetable_day_of_week_timetable_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='date_of_birth',
        ),
    ]
