# Generated by Django 5.0.2 on 2024-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_alter_exam_created_by_alter_studentanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
    ]
